apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: stephendemo34
  description: check path prefix
spec:
  type: openapi
  lifecycle: experimental
  owner: lab49-poc
  definition:
    $text: https://github.com/lab49-poc/stephendemo34/blob/master/src/main/resources/api-docs.yaml
