apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "stephendemo34"
  description: "check path prefix"
  annotations:
    github.com/project-slug: lab49-poc/stephendemo34
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - springboot
    - kubernetes
  links:
    - title: health status
      ### DATA_PLANE_LB needs to be configured and plugged in
      url: https://a20df726a16ea4cbdb91c30c2f82a6b2-1628815465.ap-southeast-2.elb.amazonaws.com/stephendemo34/actuator/health
      icon: dashboard
      ### domain name needs to be configured
    - title: kong manager
      url: http://a3f9fd27125c640cc8ce3f1d4f2ae5b0-1987737800.ap-southeast-2.elb.amazonaws.com:8002/overview
      icon: dashboard
      
spec:
  type: service
  lifecycle: experimental
  owner: "teama"
  providesApis:
    - stephendemo34
  consumesApis:
    - willer
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: stephendemo34
  description: check path prefix
spec:
  type: openapi
  lifecycle: experimental
  owner: lab49-poc
  definition:
    $text: https://github.com/lab49-poc/stephendemo34/blob/master/src/main/resources/api-docs.yaml
