apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "stephendemo34"
  description: "check path prefix"
  annotations:
    github.com/project-slug: lab49-poc/stephendemo34
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - springboot
    - kubernetes
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
spec:
  type: service
  lifecycle: experimental
  owner: "teama"
  providesApis:
    - stephendemo34
#  consumesApis:
#    - petstore
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: stephendemo34
  description: check path prefix
spec:
  type: openapi
  lifecycle: experimental
  owner: lab49-poc
  definition:
    $text: https://github.com/lab49-poc/stephendemo34/blob/master/src/main/resources/api-docs.yaml
